"""Train an AVC model on BBBC021 using one-hot perturbation conditioning.
This is the IID pretraining step. To generalise to unseen compounds,
you can then take a checkpoint generated by this script and run finetune.py
to finetune with Morgan fingerprint embeddings.
"""

import logging
import os
import pathlib

import ornamentalist
import submitit
import torch
import wandb
from torch.nn.parallel import DistributedDataParallel as DDP

import bbbc021
from model import get_model_cls
from trainer import TrainState, train
from utils.distributed import Distributed
from utils.ema import KarrasEMA
from utils.launcher import launch
from utils.name_run import generate_random_name

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)


def prng(rank: int, seed: int = 42):
    local_seed = seed + rank
    torch.manual_seed(local_seed)
    torch.cuda.manual_seed(local_seed)
    log.info(f"Rank {rank} setting seed to {local_seed}")


def main(config: ornamentalist.ConfigDict):
    ornamentalist.setup(config, force=True)
    with Distributed() as D:
        job_env = submitit.JobEnvironment()

        cwd = pathlib.Path.cwd()
        output_dir = str(cwd.parent / job_env.job_id)
        name = generate_random_name(output_dir)

        if D.rank == 0:
            wandb.init(
                name=name,
                id=name,
                dir=output_dir,
                notes=f"Outputs saved to: {output_dir}",
                project="avc",
                resume="allow",
                save_code=False,
                config=config,
            )

        log.info(f"Running job ID {job_env.job_id}")
        log.info(f"{output_dir=}")
        log.info(f"{name=}")
        log.info(f"{config=}")

        prng(D.rank)
        torch.set_float32_matmul_precision("medium")

        model_cls = get_model_cls(name="DiT-XL/2")
        net = model_cls(
            in_channels=bbbc021.IMG_CHANNELS,
            input_size=bbbc021.IMG_SIZE,
            y_dim=bbbc021.NUM_PERTURBATIONS,
            e_dim=bbbc021.NUM_EXPERIMENTS,
            c_dim=bbbc021.NUM_CELL_TYPES,
        )
        net.to(D.device)
        net.compile()
        ddp = DDP(net)
        ema = KarrasEMA(net)
        opt = torch.optim.Adam(
            net.parameters(),
            lr=1e-4,
            betas=(0.9, 0.999),
            eps=1e-8,
            weight_decay=0.0,
        )
        state = TrainState(ddp=ddp, ema=ema, opt=opt, global_step=0)

        ckpt_dir = os.path.join(output_dir, "checkpoints")
        os.makedirs(ckpt_dir, exist_ok=True)
        log.info(f"Using checkpoint directory: {ckpt_dir}")
        state.load_latest_ckpt(dir=ckpt_dir, device=D.device)

        train_loader, iid_loader, _ = bbbc021.get_dataloaders()
        train(
            state=state,
            train_loader=train_loader,
            val_loader=iid_loader,
            test_loaders={"iid": iid_loader},
            output_dir=output_dir,
            D=D,
        )

        if D.rank == 0:
            wandb.finish(quiet=True)


if __name__ == "__main__":
    configs = ornamentalist.cli()
    assert all(config["launcher"] == configs[0]["launcher"] for config in configs)
    ornamentalist.setup(configs[0], force=True)
    launch(main, configs=configs)
